services:

  db:
    build: ./db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

  app:
    build: ./app
    ports:
      - 8080:8080
    environment:
      APP_HOST: app
      APP_PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
