CREATE DATABASE logs
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

GRANT ALL ON DATABASE logs TO postgres;
GRANT TEMPORARY, CONNECT ON DATABASE logs TO PUBLIC;
GRANT ALL PRIVILEGES ON DATABASE logs TO postgres;

\c logs;

CREATE TABLE log (
    id SERIAL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    message TEXT NOT NULL
) PARTITION BY RANGE (created);

